export const doctors = [
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `4.5`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `4.4`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `3.8`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `4.8`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `3.6`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `4.8`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `4.5`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `2.8`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },

  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `4.8`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `2.5`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `3.8`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
  {
    name: `John Morgan`,
    img: `https://xmed.uz/_next/image/?url=https%3A%2F%2Fprod.xmed.uz%2Fimages%2Fdoctor_images%2F56464171.png&w=256&q=75`,
    rate: `3.0`,
    specialization: `Dermatologist`,
    experience: `10 years`,
    location: `Tashkent, Uzbekistan`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`,
    language: `uz | ru`,
    price: `10 000 so'm`,
  },
];
